name: Keep App Awake
on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 6 hours
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://rag-document-chatbot-dnent3vrb5bwnzsd7zpovz.streamlit.app/
